### PR TITLE
Filter private IPs according to spec in rfc1918

### PR DESCRIPTION
**Pull request by linknum23**
As suggested by @bs42. Tested on the latest HA: 2022.12.8

### CODE REVIEW

**Comment by bs42** [comment]
172.16/12 doesn't mean 16 and 12, it is CIDR notation meaning  the IPs between 172.16.0.0  and 172.31.255.255.

Another option might be to use the python ipaddress module as it can do all the checks to see if an IP is within a range.

**Comment by linknum23** [comment]
Oops, my mistake. I'll test out a sensible alternative with that library.

**Comment by bs42** [comment]
Awesome!

**Comment by linknum23** [comment]
This needs a little more testing, still a work in progress...

**Comment by brianhealey** [comment]
I am not sure the responsibility for filtering should be on homeassistant. Can you fix your development installs to not emit invalid ip addresses instead?

**Comment by linknum23** [comment]
Yeah I think that makes a ton of sense. Sorry about this PR. I'll close this and make one that removes the filtering.

Just a heads up the last PR https://github.com/brianhealey/hacs_amplipi/pull/9 added distinct ID strings that have the MAC address embedded in them. It also had the awkward filtering that should be removed.

**Pull request closed without merging**
